### ISSUE TITLE
Prevent Inverting Already Dark Colors/Windows

### ISSUE THREAD

**Issue by alex-bloomerang** [lswank/Tranquility#10]
Not entirely sure how or if this is possible given the design of Tranquility, but I have an "enhancement" request.

Is it somehow possible to be more selective when inverting colors so that screens/windows that already have a black background stay that way? For instance, this comes up most for me when working in an IDE with a dark theme or a terminal window such as iTerm. When using Tranquility, these become extremely bright and it can be quite the pain to change their themes easily.

I know Tranquility is just inverting colors system-wide which probably means being selective is not an option, but I really wanted to mention this just to bring up the idea. If we could somehow not invert already dark colors, then Tranquility would truly stand out in as an app and would, I'd think, be even more useful as a "one stop shop" for nighttime working.

**Comment by lswank** [comment]
Looks liked I merged this one in last year. :)
