### ISSUE TITLE
needs automation hook to toggle day/night

### ISSUE THREAD

**Issue by kfix** [lswank/Tranquility#11]
Nocturne never properly [supported AppleScript](http://www.andyhuang.net/blog/2009/02/toggle-nocturne-via-quicksilve.html) or any other non-interactive way to toggle day/night mode.

I use [ControlPlane](https://github.com/dustinrue/ControlPlane) to automate most toggles on my Mac based on WiFi/GPS locality, time, monitors/BTs/LANs hooked up, etc. This includes brightness and audio volume setters.

Having a non-interactive interface to Tranquility via AppleScript or shell command would allow one to link screen color & contrast to other setters so you can have f.Lux-like solar-scheduling of your screen (or whatever crazy scheme polyphasic-sleepers may desire!)

I don't have a PR for this yet, just wondering how best this should be added.

**Comment by lswank** [comment]
Key combo totally coming, but AppleScript is going to require a pull request. Anyone who wants to give it a try, I am totally open to pull requests. :)
