### ISSUE TITLE
Disabled state is reset to on when switching apps.

### ISSUE THREAD

**Issue by kfix** [lswank/Tranquility#20]
If I "Switch to Day" or use the keyboard shortcut to do the same and then subsequently switch applications with Opt-Tab, Tranquility re-enables dark-tinting all on its own.

My Mac is running OSX 10.10.3, latest Tranquility release.

**Comment by lswank** [comment]
I was able to replicate the issue. Will be looking into this.

**Comment by lswank** [comment]
kfix, are you using multiple monitors? I can replicate the issue on multiple monitors, but not on a single monitor. Will look at it again when I am in the office with multiple monitors.

**Comment by kfix** [comment]
Yup, I have a 2 screen dorkpit.
I couldn't make heads or tails of the Tranquility Controller, but it sounds like you have a lead on it.

**Comment by MartyLake** [comment]
Triggered here too, dual monitor setup. OSX 10.9.5

**Comment by kfix** [comment]
I commented out `[self setEnabled:YES]` [here](https://github.com/lswank/Tranquility/blob/2de9ff127890cd78ec72143288905a325eebffe8/QSTranquilityController.m#L622) which fixed this for me.
However, I'm not sure if its vestigial or has a purpose, so hoping @lswank can ensure that call isn't needed anymore.

**Comment by kfix** [comment]
Applied in 6777d243dce8a80ae8d199240639bfe0c70f4379, thanks!
