### ISSUE TITLE
Issue with fullscreening a program.

### ISSUE THREAD

**Issue by SeanROlszewski** [lswank/Tranquility#3]
I love what you've done here - thanks for revitalizing a very useful program!

I noticed that when I full screen programs there's a visual anomaly - there's a line where the menu bar (now hidden since I'm full screen) normally extends to. It's not a make or break bug, but it's quite annoying. 

Mac OSX 10.8.5 user here. Not sure if this is OS dependant or not, but I thought I'd let you guys know.

**Comment by lswank** [comment]
Can't replicate on 10.9 and no one has submitted anything in over one year. Closing as wontfix.
